# Theme 
source=~/.config/themes/frappe.conf

exec = gsettings set org.gnome.desktop.interface gtk-theme 'Dracula-alt-style'				:

general {
    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba($mauveAlphaee) rgba($sapphireAlphaee) 45deg
    col.inactive_border = rgba($lavenderAlphaee)
}
