# Created by Brycen Falzone
# Everforest soft light theme for hyprtookkit

background = rgb(243, 234, 211) # Background 0
base = rgb(229, 230, 197) # Background Green
# text = rgb(112, 128, 137) # Statusline 2
text = rgb(92, 106, 114) # Foreground
alternate_base = rgb(120, 140, 1) # Modified Green
# alternate_base = rgb(58, 148, 197) # Blue
# alternate_base = rgb(147, 178, 89) # Statusline 1
# bright_text = rgb(58, 148, 197) # Blue
bright_text = rgb(248, 85, 82) # Red
accent = rgb(58, 148, 197) # Blue
accent_secondary = rgb(248, 85, 82) # Red
h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10
icon_theme = 
font_family = Sans Serif
font_family_monospace = monospace
rounding_large = 10
rounding_small = 5
