## clipboard manager settings
exec-once = clipse -listen # run listener on startup

windowrule = float on, size 622 652, stay_focused on, match:class ^(clipse)$

bind = SUPER, V, exec,  kitty --class clipse -e clipse

# Example: bind = SUPER, V, exec, alacritty --class clipse -e 'clipse'
